name: CI for Develop

on:
  push:
    branches:
      - develop

jobs:
  lint-and-build:
    name: Lint and Build Services
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      # Set up Docker environment
      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-compose

      # Install dependencies for linting
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8

      # Lint the Python code
      - name: Run Flake8 Linter
        run: |
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      # Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Build and run Docker Compose services
      - name: Build and Run Docker Compose Services
        run: |
          docker-compose up --build -d
          
      # Verify containers are running
      - name: Verify running containers
        run: docker ps
